// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhSGaTLYsm1YzUSeACc-E7zBUHlE8-cUA',
    appId: '1:583660859543:web:10c047489f1ce2199a39d2',
    messagingSenderId: '583660859543',
    projectId: 'syncwave-23d08',
    authDomain: 'syncwave-23d08.firebaseapp.com',
    storageBucket: 'syncwave-23d08.firebasestorage.app',
    measurementId: 'G-0HF50CMXZS',
    databaseURL: 'https://syncwave-23d08-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1FfAxYO-gVTqrr1DW1kCWmqZi-V35P00',
    appId: '1:583660859543:android:95baf4f4935962989a39d2',
    messagingSenderId: '583660859543',
    projectId: 'syncwave-23d08',
    storageBucket: 'syncwave-23d08.firebasestorage.app',
    databaseURL: 'https://syncwave-23d08-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2oa_NYyMobBmu8wRzYfyrvMmEbQqAGSs',
    appId: '1:583660859543:ios:814c73745bb558d79a39d2',
    messagingSenderId: '583660859543',
    projectId: 'syncwave-23d08',
    storageBucket: 'syncwave-23d08.firebasestorage.app',
    iosBundleId: 'com.example.syncwave',
    databaseURL: 'https://syncwave-23d08-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhSGaTLYsm1YzUSeACc-E7zBUHlE8-cUA',
    appId: '1:583660859543:web:5d2e34a60abc52ba9a39d2',
    messagingSenderId: '583660859543',
    projectId: 'syncwave-23d08',
    authDomain: 'syncwave-23d08.firebaseapp.com',
    storageBucket: 'syncwave-23d08.firebasestorage.app',
    measurementId: 'G-73R6D91NLY',
    databaseURL: 'https://syncwave-23d08-default-rtdb.firebaseio.com',
  );
}
